version: "3.8"
services:
  react-app:
    container_name: manage_console
    build:
      context: .
      dockerfile: ./dev/front.dockerfile
    tty: true
    volumes:
      - .:/app:cached
      - react_node_modules:/app/node_modulescd
    ports:
      - 8010:80

volumes:
  react_node_modules:
