name: Deploy-Api

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

env:
  TEMPLATE_FILE: backend/deploy/api-sam-template.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Build Go Lambda Function
        run: |
          cd backend/src/lambda_handler/api_for_public
          GOOS=linux GOARCH=amd64 go build -o bootstrap
          zip main.zip bootstrap
      - name: Setup aws-sam
        uses: aws-actions/setup-sam@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: ${{secrets.AWS_REGION}}
          role-to-assume: ${{secrets.IAM_ROLE_ARN}}

      - run: aws sts get-caller-identity

      - name: Build & Deploy Cloudformation stacks
        run: |
          sam build --template-file ${TEMPLATE_FILE}
          sam deploy --template-file ${TEMPLATE_FILE} --stack-name apiForPublic --no-confirm-changeset --no-fail-on-empty-changeset
